### ISSUE TITLE
app.UseRequestTelemetryEnhancer() suck unhandled exceptions

### ISSUE THREAD

**Issue by TheDevKnight** [gilad-teller/ApplicationInsightsTelemetryEnhancer#2]
HI,

nice extension for AI 👍 

But i found out that the use of the app.UseRequestTelemetryEnhancer() in this.Configure(...) is the reason that my azure app service (.NET 5.0 in Linux 64bit) will not send the Exception to my Appication Insights instance. 
The use will also return a HTTP 200 Response when an unhandled exception is thrown. This is not so good because my client think that the every thing is ok an crashed at the JSON parsing :(

You could simply reproduce it with the default web API template. Added a second Controller that throws an exception.

Is it possible to chanmge this behavior and rethrow an unhandled exception in the middleware?

Regards

**Comment by gilad-teller** [comment]
You are absolutely correct!
Thanks for the heads up.
One problem with your fix is that the operation-id header is missing if an exception is thrown. I will look into it.

**Comment by TheDevKnight** [comment]
Ah ok, i don't use the operation id header. I will wait for your fix 😉👍

**Comment by gilad-teller** [comment]
A new version has been published!
You can get it from Nuget or from the release section here on GitHub.
The master branch is updated with the fix.

**Comment by TheDevKnight** [comment]
works + thx 👍
